title: SCP-4587
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
remote_theme: pages-themes/tactile@v0.2.0
relative_links:
  enabled: true
  collections: true
include:
  - SCP-4587.md
  - Addendum/4587-A
  - Addendum/4587-B
